### ISSUE TITLE
Update README for Projest

### ISSUE THREAD

**Issue by Frenziecodes** [Frenziecodes/Projest#104]
### Description

The current README for the Projest project needs some updates to reflect the latest changes and provide accurate information about the project. This will help users and contributors have a better understanding of the project and its current state.

### Tasks
- [ ] Modify the "Getting Started" section to provide clear instructions for running the app.
- [ ] Add a section on contributing to the project.
- [ ] Mention the availability of support and encourage users to open issues.
- [ ] Request users to consider giving the repository a star.

### Acceptance Criteria
- The README is updated with accurate and up-to-date information.
- The "Getting Started" section provides clear instructions for running the app.
- A new section on contributing to the project is added.
- Information about support and issue reporting is included.
- A request to star the repository is added to the README.
